"""add_fanpage_verification_fields

Revision ID: 229b3ebe66a5
Revises: e55512d50e3d
Create Date: 2026-03-18 16:23:40.617246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229b3ebe66a5'
down_revision: Union[str, None] = 'e55512d50e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fanpages', sa.Column('verification_status', sa.String(), server_default='UNVERIFIED', nullable=False))
    op.add_column('fanpages', sa.Column('verification_error', sa.String(), nullable=True))
    op.add_column('fanpages', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fanpages', 'verified_at')
    op.drop_column('fanpages', 'verification_error')
    op.drop_column('fanpages', 'verification_status')
    # ### end Alembic commands ###
