"""add_posts_per_day_to_campaigns

Revision ID: 2dda02426933
Revises: a93b6a0dae39
Create Date: 2026-03-12 14:40:58.094167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dda02426933'
down_revision: Union[str, None] = 'a93b6a0dae39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('posts_per_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'posts_per_day')
    # ### end Alembic commands ###
