"""add_schedule_fields_to_campaigns

Revision ID: a93b6a0dae39
Revises: d5a3b7e29f81
Create Date: 2026-03-12 14:08:50.588748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93b6a0dae39'
down_revision: Union[str, None] = 'd5a3b7e29f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('active_hours_start', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('active_hours_end', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('active_days', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'active_days')
    op.drop_column('campaigns', 'active_hours_end')
    op.drop_column('campaigns', 'active_hours_start')
    # ### end Alembic commands ###
