"""add_fanpages_table

Revision ID: e55512d50e3d
Revises: 4d539d4fdfec
Create Date: 2026-03-18 15:21:06.945532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55512d50e3d'
down_revision: Union[str, None] = '4d539d4fdfec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fanpages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('fanpage_url', sa.String(), nullable=False),
    sa.Column('fanpage_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fanpages_id'), 'fanpages', ['id'], unique=False)
    op.create_unique_constraint('uq_fanpages_account_url', 'fanpages', ['account_id', 'fanpage_url'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fanpages_account_url', 'fanpages', type_='unique')
    op.drop_index(op.f('ix_fanpages_id'), table_name='fanpages')
    op.drop_table('fanpages')
    # ### end Alembic commands ###
